---
location: eastus
resource_group: rg-pilot-staging
env: staging

vnet_name: vnet-pilot-staging
vnet_cidr: 10.1.0.0/16
subnet_name: snet-pilot-staging
subnet_cidr: 10.1.1.0/24

vm_name: vm-pilot-staging
vm_size: Standard_B2s

aks_cluster_name: aks-pilot-staging
aks_dns_prefix: aks-pilot-staging
aks_node_count: 2
aks_node_size: Standard_DS2_v2

app_gateway_name: agw-pilot-staging
app_gateway_subnet_name: snet-pilot-staging-agw
app_gateway_subnet_cidr: 10.1.2.0/24
