---
- name: Create AKS cluster
  azure.azcollection.azure_rm_aks:
    resource_group: "{{ resource_group }}"
    name: "{{ aks_cluster_name }}"
    dns_prefix: "{{ aks_dns_prefix }}"
    agent_pool_profiles:
      - name: default
        count: "{{ aks_node_count }}"
        vm_size: "{{ aks_node_size }}"
    linux_profile:
      admin_username: azureuser
      ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    tags:
      environment: "{{ env }}"
      role: aks
