---
- name: Create Azure resource group
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: "{{ location }}"
    tags:
      environment: "{{ env }}"
      project: pilot
