---
- name: Create Application Gateway public IP
  azure.azcollection.azure_rm_publicipaddress:
    resource_group: "{{ resource_group }}"
    name: "{{ app_gateway_public_ip_name }}"
    allocation_method: Static
    sku: Standard

- name: Create Application Gateway subnet
  azure.azcollection.azure_rm_subnet:
    resource_group: "{{ resource_group }}"
    name: "{{ app_gateway_subnet_name }}"
    address_prefix: "{{ app_gateway_subnet_cidr }}"
    virtual_network: "{{ vnet_name }}"

- name: Create Application Gateway
  azure.azcollection.azure_rm_appgateway:
    resource_group: "{{ resource_group }}"
    location: "{{ location }}"
    name: "{{ app_gateway_name }}"
    sku:
      name: "{{ app_gateway_sku_name }}"
      tier: "{{ app_gateway_sku_tier }}"
      capacity: "{{ app_gateway_capacity }}"
    gateway_ip_configurations:
      - name: "{{ app_gateway_gateway_ip_configuration_name }}"
        subnet:
          name: "{{ app_gateway_subnet_name }}"
          virtual_network_name: "{{ vnet_name }}"
    frontend_ip_configurations:
      - name: "{{ app_gateway_frontend_ip_configuration_name }}"
        public_ip_address: "{{ app_gateway_public_ip_name }}"
    frontend_ports:
      - name: "{{ app_gateway_frontend_port_name }}"
        port: "{{ app_gateway_frontend_port }}"
    backend_address_pools:
      - name: "{{ app_gateway_backend_address_pool_name }}"
    backend_http_settings_collection:
      - name: "{{ app_gateway_backend_http_settings_name }}"
        port: "{{ app_gateway_backend_port }}"
        protocol: http
        cookie_based_affinity: disabled
        request_timeout: 30
    http_listeners:
      - name: "{{ app_gateway_http_listener_name }}"
        protocol: http
        frontend_ip_configuration: "{{ app_gateway_frontend_ip_configuration_name }}"
        frontend_port: "{{ app_gateway_frontend_port_name }}"
    request_routing_rules:
      - name: "{{ app_gateway_request_routing_rule_name }}"
        rule_type: basic
        priority: 100
        http_listener: "{{ app_gateway_http_listener_name }}"
        backend_address_pool: "{{ app_gateway_backend_address_pool_name }}"
        backend_http_settings: "{{ app_gateway_backend_http_settings_name }}"
    tags:
      environment: "{{ env }}"
      role: application_gateway